//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код был создан программным средством.
//
//     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
//     код создается повторно. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicturesSecurity.Account {
    
    
    public partial class Confirm {
        
        /// <summary>
        /// Элемент управления successPanel.
        /// </summary>
        /// <remarks>
        /// Автоматически созданное поле.
        /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder successPanel;
        
        /// <summary>
        /// Элемент управления login.
        /// </summary>
        /// <remarks>
        /// Автоматически созданное поле.
        /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink login;
        
        /// <summary>
        /// Элемент управления errorPanel.
        /// </summary>
        /// <remarks>
        /// Автоматически созданное поле.
        /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder errorPanel;

    }
}
